import Player from './Player';
import { render, screen } from '@testing-library/react';
import { act } from "react-dom/test-utils";
import axios from 'axios'
import { Routes, Route, BrowserRouter, Router } from "react-router-dom";

test('test Player component', async () => {
  jest.spyOn(axios, 'get').mockResolvedValue({"data": 
    {
      "name": "大谷　翔平",
      "birth": "1994.7.5生",
      "bt": "右投左打",
      "rate": 1516,
      "pitching": [
        {
          "year": "2013",
          "game": 13,
          "starter": 11,
          "cg": 0,
          "shutout": 0,
          "win": 3,
          "lose": 0,
          "save": 0,
          "hold": 0,
          "inning": 61.2,
          "k": 46,
          "era": 4.23,
          "whip": 1.46,
          "mlb": false
        },
        {
          "year": "2014",
          "game": 24,
          "starter": 24,
          "cg": 3,
          "shutout": 2,
          "win": 11,
          "lose": 4,
          "save": 0,
          "hold": 0,
          "inning": 155.1,
          "k": 179,
          "era": 2.61,
          "whip": 1.17,
          "mlb": false
        },
        {
          "year": "2015",
          "game": 22,
          "starter": 22,
          "cg": 5,
          "shutout": 3,
          "win": 15,
          "lose": 5,
          "save": 0,
          "hold": 0,
          "inning": 160.2,
          "k": 196,
          "era": 2.24,
          "whip": 0.91,
          "mlb": false
        },
        {
          "year": "2016",
          "game": 21,
          "starter": 20,
          "cg": 4,
          "shutout": 1,
          "win": 10,
          "lose": 4,
          "save": 0,
          "hold": 1,
          "inning": 140,
          "k": 174,
          "era": 1.86,
          "whip": 0.96,
          "mlb": false
        },
        {
          "year": "2017",
          "game": 5,
          "starter": 5,
          "cg": 1,
          "shutout": 1,
          "win": 3,
          "lose": 2,
          "save": 0,
          "hold": 0,
          "inning": 25.1,
          "k": 29,
          "era": 3.2,
          "whip": 1.26,
          "mlb": false
        },
        {
          "year": "2018",
          "game": 10,
          "starter": 10,
          "cg": 0,
          "shutout": 0,
          "win": 4,
          "lose": 2,
          "save": 0,
          "hold": 0,
          "inning": 51.2,
          "k": 63,
          "era": 3.31,
          "whip": 1.16,
          "mlb": true
        },
        {
          "year": "2019",
          "game": 0,
          "starter": 0,
          "cg": 0,
          "shutout": 0,
          "win": 0,
          "lose": 0,
          "save": 0,
          "hold": 0,
          "inning": 0,
          "k": 0,
          "era": 0,
          "whip": 0,
          "mlb": true
        },
        {
          "year": "2020",
          "game": 2,
          "starter": 2,
          "cg": 0,
          "shutout": 0,
          "win": 0,
          "lose": 1,
          "save": 0,
          "hold": 0,
          "inning": 1.2,
          "k": 3,
          "era": 37.8,
          "whip": 6.6,
          "mlb": true
        },
        {
          "year": "2021",
          "game": 23,
          "starter": 23,
          "cg": 0,
          "shutout": 0,
          "win": 9,
          "lose": 2,
          "save": 0,
          "hold": 0,
          "inning": 130.1,
          "k": 156,
          "era": 3.18,
          "whip": 1.09,
          "mlb": true
        },
        {
          "year": "国内通算",
          "game": 85,
          "starter": 82,
          "cg": 13,
          "shutout": 7,
          "win": 42,
          "lose": 15,
          "save": 0,
          "hold": 1,
          "inning": 543,
          "k": 624,
          "era": 2.52,
          "whip": 1.08,
          "mlb": false
        },
        {
          "year": "MLB通算",
          "game": 35,
          "starter": 35,
          "cg": 0,
          "shutout": 0,
          "win": 13,
          "lose": 5,
          "save": 0,
          "hold": 0,
          "inning": 183.2,
          "k": 222,
          "era": 3.53,
          "whip": 1.16,
          "mlb": true
        }
      ],
      "batting": [
        {
          "year": "2013",
          "game": 77,
          "pa": 204,
          "atbat": 189,
          "hit": 45,
          "twoBase": 15,
          "threeBase": 1,
          "hr": 3,
          "rbi": 20,
          "sb": 4,
          "cs": 1,
          "sh": 0,
          "sf": 2,
          "bb": 12,
          "iw": 0,
          "hbp": 1,
          "so": 64,
          "avg": 0.238,
          "obp": 0.284,
          "slg": 0.376,
          "ops": 0.66,
          "mlb": false
        },
        {
          "year": "2014",
          "game": 87,
          "pa": 234,
          "atbat": 212,
          "hit": 58,
          "twoBase": 17,
          "threeBase": 1,
          "hr": 10,
          "rbi": 31,
          "sb": 1,
          "cs": 0,
          "sh": 0,
          "sf": 1,
          "bb": 21,
          "iw": 0,
          "hbp": 0,
          "so": 48,
          "avg": 0.274,
          "obp": 0.338,
          "slg": 0.505,
          "ops": 0.842,
          "mlb": false
        },
        {
          "year": "2015",
          "game": 70,
          "pa": 119,
          "atbat": 109,
          "hit": 22,
          "twoBase": 4,
          "threeBase": 0,
          "hr": 5,
          "rbi": 17,
          "sb": 1,
          "cs": 0,
          "sh": 0,
          "sf": 2,
          "bb": 8,
          "iw": 1,
          "hbp": 0,
          "so": 43,
          "avg": 0.202,
          "obp": 0.252,
          "slg": 0.376,
          "ops": 0.628,
          "mlb": false
        },
        {
          "year": "2016",
          "game": 104,
          "pa": 382,
          "atbat": 323,
          "hit": 104,
          "twoBase": 18,
          "threeBase": 1,
          "hr": 22,
          "rbi": 67,
          "sb": 7,
          "cs": 2,
          "sh": 0,
          "sf": 4,
          "bb": 54,
          "iw": 2,
          "hbp": 1,
          "so": 98,
          "avg": 0.322,
          "obp": 0.416,
          "slg": 0.588,
          "ops": 1.004,
          "mlb": false
        },
        {
          "year": "2017",
          "game": 65,
          "pa": 231,
          "atbat": 202,
          "hit": 67,
          "twoBase": 16,
          "threeBase": 1,
          "hr": 8,
          "rbi": 31,
          "sb": 0,
          "cs": 1,
          "sh": 0,
          "sf": 3,
          "bb": 24,
          "iw": 0,
          "hbp": 2,
          "so": 63,
          "avg": 0.332,
          "obp": 0.403,
          "slg": 0.54,
          "ops": 0.942,
          "mlb": false
        },
        {
          "year": "2018",
          "game": 104,
          "pa": 367,
          "atbat": 326,
          "hit": 93,
          "twoBase": 21,
          "threeBase": 2,
          "hr": 22,
          "rbi": 61,
          "sb": 10,
          "cs": 4,
          "sh": 0,
          "sf": 1,
          "bb": 37,
          "iw": 2,
          "hbp": 2,
          "so": 102,
          "avg": 0.285,
          "obp": 0.361,
          "slg": 0.564,
          "ops": 0.925,
          "mlb": true
        },
        {
          "year": "2019",
          "game": 106,
          "pa": 425,
          "atbat": 384,
          "hit": 110,
          "twoBase": 20,
          "threeBase": 5,
          "hr": 18,
          "rbi": 62,
          "sb": 12,
          "cs": 3,
          "sh": 0,
          "sf": 4,
          "bb": 33,
          "iw": 1,
          "hbp": 2,
          "so": 110,
          "avg": 0.286,
          "obp": 0.343,
          "slg": 0.505,
          "ops": 0.848,
          "mlb": true
        },
        {
          "year": "2020",
          "game": 44,
          "pa": 175,
          "atbat": 153,
          "hit": 29,
          "twoBase": 6,
          "threeBase": 0,
          "hr": 7,
          "rbi": 24,
          "sb": 7,
          "cs": 1,
          "sh": 0,
          "sf": 0,
          "bb": 22,
          "iw": 0,
          "hbp": 0,
          "so": 50,
          "avg": 0.19,
          "obp": 0.291,
          "slg": 0.366,
          "ops": 0.657,
          "mlb": true
        },
        {
          "year": "2021",
          "game": 155,
          "pa": 639,
          "atbat": 537,
          "hit": 138,
          "twoBase": 26,
          "threeBase": 8,
          "hr": 46,
          "rbi": 100,
          "sb": 26,
          "cs": 10,
          "sh": 0,
          "sf": 2,
          "bb": 96,
          "iw": 20,
          "hbp": 4,
          "so": 189,
          "avg": 0.257,
          "obp": 0.372,
          "slg": 0.592,
          "ops": 0.965,
          "mlb": true
        },
        {
          "year": "国内通算",
          "game": 403,
          "pa": 1170,
          "atbat": 1035,
          "hit": 296,
          "twoBase": 70,
          "threeBase": 4,
          "hr": 48,
          "rbi": 166,
          "sb": 13,
          "cs": 4,
          "sh": 0,
          "sf": 12,
          "bb": 119,
          "iw": 3,
          "hbp": 4,
          "so": 316,
          "avg": 0.286,
          "obp": 0.358,
          "slg": 0.5,
          "ops": 0.858,
          "mlb": false
        },
        {
          "year": "MLB通算",
          "game": 409,
          "pa": 1606,
          "atbat": 1400,
          "hit": 370,
          "twoBase": 73,
          "threeBase": 15,
          "hr": 93,
          "rbi": 247,
          "sb": 55,
          "cs": 18,
          "sh": 0,
          "sf": 7,
          "bb": 188,
          "iw": 23,
          "hbp": 8,
          "so": 451,
          "avg": 0.264,
          "obp": 0.353,
          "slg": 0.537,
          "ops": 0.89,
          "mlb": true
        }
      ]
    }
  });

  render(
    <Player />
  )

  //[TODO] I want to increase test coverage...
  expect(await screen.findByText(/大谷.+翔平/)).toBeInTheDocument();
  expect(await screen.findByText(/624/)).toBeInTheDocument();
  expect(await screen.findByText(/1.004/)).toBeInTheDocument();
});