import Vote from './Vote';
import { render, screen } from '@testing-library/react';
import axios from 'axios'

test('test Vote component', async () => {
  jest.spyOn(axios, 'get').mockResolvedValue({"data":
  {
    "error": false,
    "token": "28389e8162bd9522b1c301eeadf4da96",
    "player1": {
      "id": 867,
      "name": "堂上　照",
      "birth": "1951.6.9生",
      "bt": "右投右打",
      "pitchingCareerHigh": {
        "year": "1982",
        "game": 28,
        "starter": 4,
        "cg": 0,
        "shutout": 0,
        "win": 1,
        "lose": 0,
        "save": 0,
        "hold": 0,
        "inning": 65.1,
        "k": 42,
        "era": 1.25,
        "whip": 0.99,
        "mlb": false
      },
      "battingCareerHigh": {
        "year": "1980",
        "game": 33,
        "pa": 47,
        "atbat": 41,
        "hit": 12,
        "twoBase": 2,
        "threeBase": 1,
        "hr": 1,
        "rbi": 3,
        "sb": 0,
        "cs": 0,
        "sh": 6,
        "sf": 0,
        "bb": 0,
        "iw": 0,
        "hbp": 0,
        "so": 11,
        "avg": 0.293,
        "obp": 0.293,
        "slg": 0.463,
        "ops": 0.756,
        "mlb": false
      },
      "pitchingTotal": {
        "year": "国内通算",
        "game": 320,
        "starter": 97,
        "cg": 9,
        "shutout": 5,
        "win": 35,
        "lose": 49,
        "save": 7,
        "hold": 0,
        "inning": 874.1,
        "k": 345,
        "era": 4.36,
        "whip": 1.43,
        "mlb": false
      },
      "battingTotal": {
        "year": "国内通算",
        "game": 325,
        "pa": 235,
        "atbat": 213,
        "hit": 49,
        "twoBase": 10,
        "threeBase": 3,
        "hr": 4,
        "rbi": 23,
        "sb": 0,
        "cs": 0,
        "sh": 17,
        "sf": 1,
        "bb": 3,
        "iw": 0,
        "hbp": 1,
        "so": 59,
        "avg": 0.23,
        "obp": 0.243,
        "slg": 0.362,
        "ops": 0.605,
        "mlb": false
      },
      "pitchingMLBTotal": {
        "year": "",
        "game": 0,
        "starter": 0,
        "cg": 0,
        "shutout": 0,
        "win": 0,
        "lose": 0,
        "save": 0,
        "hold": 0,
        "inning": 0,
        "k": 0,
        "era": 0,
        "whip": 0,
        "mlb": false
      },
      "battingMLBTotal": {
        "year": "",
        "game": 0,
        "pa": 0,
        "atbat": 0,
        "hit": 0,
        "twoBase": 0,
        "threeBase": 0,
        "hr": 0,
        "rbi": 0,
        "sb": 0,
        "cs": 0,
        "sh": 0,
        "sf": 0,
        "bb": 0,
        "iw": 0,
        "hbp": 0,
        "so": 0,
        "avg": 0,
        "obp": 0,
        "slg": 0,
        "ops": 0,
        "mlb": false
      }
    },
    "player2": {
      "id": 65,
      "name": "寺内　一隆",
      "birth": "1912.9.3生",
      "bt": "右投右打",
      "pitchingCareerHigh": {
        "year": "",
        "game": 0,
        "starter": 0,
        "cg": 0,
        "shutout": 0,
        "win": 0,
        "lose": 0,
        "save": 0,
        "hold": 0,
        "inning": 0,
        "k": 0,
        "era": 0,
        "whip": 0,
        "mlb": false
      },
      "battingCareerHigh": {
        "year": "1939",
        "game": 93,
        "pa": 408,
        "atbat": 345,
        "hit": 71,
        "twoBase": 17,
        "threeBase": 9,
        "hr": 4,
        "rbi": 24,
        "sb": 3,
        "cs": 0,
        "sh": 4,
        "sf": 1,
        "bb": 57,
        "iw": 0,
        "hbp": 1,
        "so": 35,
        "avg": 0.206,
        "obp": 0.32,
        "slg": 0.342,
        "ops": 0.662,
        "mlb": false
      },
      "pitchingTotal": {
        "year": "",
        "game": 0,
        "starter": 0,
        "cg": 0,
        "shutout": 0,
        "win": 0,
        "lose": 0,
        "save": 0,
        "hold": 0,
        "inning": 0,
        "k": 0,
        "era": 0,
        "whip": 0,
        "mlb": false
      },
      "battingTotal": {
        "year": "国内通算",
        "game": 419,
        "pa": 1715,
        "atbat": 1440,
        "hit": 283,
        "twoBase": 41,
        "threeBase": 17,
        "hr": 13,
        "rbi": 104,
        "sb": 28,
        "cs": 2,
        "sh": 24,
        "sf": 1,
        "bb": 245,
        "iw": 0,
        "hbp": 5,
        "so": 194,
        "avg": 0.197,
        "obp": 0.315,
        "slg": 0.276,
        "ops": 0.591,
        "mlb": false
      },
      "pitchingMLBTotal": {
        "year": "",
        "game": 0,
        "starter": 0,
        "cg": 0,
        "shutout": 0,
        "win": 0,
        "lose": 0,
        "save": 0,
        "hold": 0,
        "inning": 0,
        "k": 0,
        "era": 0,
        "whip": 0,
        "mlb": false
      },
      "battingMLBTotal": {
        "year": "",
        "game": 0,
        "pa": 0,
        "atbat": 0,
        "hit": 0,
        "twoBase": 0,
        "threeBase": 0,
        "hr": 0,
        "rbi": 0,
        "sb": 0,
        "cs": 0,
        "sh": 0,
        "sf": 0,
        "bb": 0,
        "iw": 0,
        "hbp": 0,
        "so": 0,
        "avg": 0,
        "obp": 0,
        "slg": 0,
        "ops": 0,
        "mlb": false
      }
    }
  }});
  render(<Vote />);

  await screen.findAllByRole("button");

  //[TODO] I want to increase test coverage...
  expect(screen.getByText(/堂上.+照/)).toBeInTheDocument();
  expect(screen.getByText(/寺内.+一隆/)).toBeInTheDocument();
});